process.env.MY_CUSTOM_TEST_ENV_VAR = "foo";
process.env.DB_URL = "mongodb://127.0.0.1/test";
process.env.CLIENT_URL = "localhost:5173";
process.env.BCRYPT_SALT = "10";
process.env.EMAIL_POSTMARK_SERVER_CLIENT =
  "24f31933-6b74-486d-903f-cbd3a32cb30b";
process.env.EMAIL_HOST = "smtp.zoho.com";
process.env.EMAIL_USERNAME = "evanparker@everyminipainted.com";
process.env.EMAIL_PORT = "465";
process.env.EMAIL_PASSWORD = "undefined";
process.env.FROM_EMAIL = "evanparker@everyminipainted.com";
process.env.AWS_S3_BUCKET = "every-mini-painted";
process.env.AWS_REGION = "us-west-2";
process.env.AWS_ACCESS_KEY_ID = "undefined";
process.env.AWS_SECRET_ACCESS_KEY = "undefined";
process.env.EDIT_FIGURE_REQUIRES_ADMIN = "true";
process.env.EDIT_MANUFACTURER_REQUIRES_ADMIN = "true";
process.env.EDIT_COLLECTION_REQUIRES_ADMIN = "true";
process.env.CREATE_USER_REQUIRES_INVITE = "true";
